#!/usr/bin/env bash

url=https://github.com
# account=ThePrimeagen
# declare -a repos=("harpoon" "vim-fundamentals" ".dotfiles" "dev-productivity" "ansible" "ansible-dev-prod" "ansible-dev-prod" "fem-vim")


 account=elixir-lang
 declare -a repos=( "elixir" "ex_doc" "tree-sitter-elixir" "tree-sitter-iex" "elixir_make")

mkdir "$account"

for repo in "${repos[@]}"
do
  folder=$(echo $repo | tr . _)
  git clone $url/$account/$repo.git $account/$folder
done

